name: ldm
# This file is part of stable-diffusion-webui (https://github.com/sd-webui/stable-diffusion-webui/).

# Copyright 2022 sd-webui team.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 
channels:
  - pytorch
  - defaults
# Psst. If you change a dependency, make sure it's mirrored in the docker requirement
# files as well.
dependencies:
  - cudatoolkit=11.3
  - git
  - numpy=1.22.3
  - pip=20.3
  - python=3.8.5
  - pytorch=1.11.0
  - scikit-image=0.19.2
  - torchvision=0.12.0
  - pip:
    - -e .
    - -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP#egg=clip
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
    - -e git+https://github.com/devilismyfriend/latent-diffusion#egg=latent-diffusion
    - accelerate==0.12.0
    - albumentations==0.4.3
    - basicsr>=1.3.4.0
    - diffusers==0.3.0
    - einops==0.3.0
    - facexlib>=0.2.3
    - gradio==3.1.6
    - imageio-ffmpeg==0.4.2
    - imageio==2.9.0
    - kornia==0.6
    - omegaconf==2.1.1
    - opencv-python-headless==4.6.0.66
    - pandas==1.4.3
    - piexif==1.1.3
    - pudb==2019.2
    - pynvml==11.4.1
    - python-slugify>=6.1.2
    - pytorch-lightning==1.4.2
    - retry>=0.9.2
    - realesrgan==0.3.0
    - streamlit==1.13.0
    - streamlit-on-Hover-tabs==1.0.1
    - streamlit-option-menu==0.3.2
    - streamlit_nested_layout
    - streamlit-server-state==0.14.2
    - streamlit-tensorboard==0.0.2
    - test-tube>=0.7.5
    - tensorboard==2.10.1
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - transformers==4.19.2

