name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3
  - git
  - numpy=1.22.3
  - pip=20.3
  - python=3.8.5
  - pytorch=1.11.0
  - scikit-image=0.19.2
  - torchvision=0.12.0
  - pip:
    - -e .
    - -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP#egg=clip
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
    - -e git+https://github.com/devilismyfriend/latent-diffusion#egg=latent-diffusion
    - accelerate==0.12.0
    - albumentations==0.4.3
    - basicsr>=1.3.4.0
    - diffusers==0.3.0
    - einops==0.3.0
    - facexlib>=0.2.3
    - gradio==3.1.6
    - imageio-ffmpeg==0.4.2
    - imageio==2.9.0
    - kornia==0.6
    - omegaconf==2.1.1
    - opencv-python-headless==4.6.0.66
    - pandas==1.4.3
    - piexif==1.1.3
    - pudb==2019.2
    - pynvml==11.4.1
    - python-slugify>=6.1.2
    - pytorch-lightning==1.4.2
    - retry>=0.9.2
    - streamlit>=1.12.2
    - streamlit-on-Hover-tabs==1.0.1
    - streamlit-option-menu==0.3.2
    - streamlit_nested_layout
    - test-tube>=0.7.5
    - tensorboard
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - transformers==4.19.2
